name: e2e_test
version: 0.0.0
author: Polymer.dart Authors <web-ui-dev@dartlang.org>
dependencies:
  custom_element_apigen:
    path: ../
  polymer_interop: ^1.0.0-rc.1
dev_dependencies:
  test: ^0.12.0
environment:
  sdk: '>=1.6.0 <2.0.0'
