name: custom_element_apigen
version: 0.1.4-dev
author: Polymer.dart Authors <web-ui-dev@dartlang.org>
description: Generates Dart API for JS Custom Elements
homepage: https://github.com/dart-lang/custom-element-apigen
dependencies:
  html5lib: ">=0.11.0 <0.13.0"
  path: ">=1.0.0 <2.0.0"
  polymer: ">=0.16.0 <0.17.0"
  yaml: ">=1.0.0 <3.0.0"
  # TODO(sigmund): maybe remove this dependency? It is required only for the
  # generated code. We could make the codegen ensure that it is listed in the
  # package pubspec instead.
  web_components: ">=0.10.2 <0.11.0"
dependency_overrides:
  polymer:
    git:
      url: https://github.com/dart-lang/polymer-dart.git
      ref: smoke-generator
environment:
  sdk: '>=1.6.0 <2.0.0'
